/** Session Storage */
export const SESSION_FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const SESSION_JWT_AUTH_DATA = "JWT_AUTH_DATA";
export const SESSION_FLASHING_ID = "FLASHING_ID";
export const SESSION_USER_PROFILE = "USER_PROFILE";
export const SESSION_ORGANIZATION = "ORGANIZATION";
export const SESSION_ORGANIZATION_NAME = "ORGANIZATION_NAME";
export const SESSION_ORGANIZATION_CACHED = "ORGANIZATION_CACHED";
export const SESSION_RETURN_URL = "RETURN_URL";
export const SESSION_ORGANIZATION_SETTING_EXTENDED = "ORGANIZATION_SETTING_EXTENDED";

/** Local Storage */
export const PERSISTENT_ORGANIZATION = "ORGANIZATION";

/** Cookie */
export const COOKIE_ORGANIZATION_CODE = "ORGANIZATION_CODE";
