// App
export const APP_START_LOADING = "APP_START_LOADING" as const;
export const APP_END_LOADING = "APP_END_LOADING" as const;
export const APP_ADD_NOTIFICATION = "APP_ADD_NOTIFICATION" as const;
export const APP_REMOVE_NOTIFICATION = "APP_REMOVE_NOTIFICATION" as const;
export const APP_CLEAR_NOTIFICATION = "APP_CLEAR_NOTIFICATION" as const;
export const APP_SET_BREADCRUMB_ITEMS = "APP_SET_BREADCRUMB_ITEMS" as const;
export const APP_CLEAR_BREADCRUMB_ITEMS = "APP_CLEAR_BREADCRUMB_ITEMS" as const;
export const APP_UPDATE_USER_PROFILE = "APP_UPDATE_USER_PROFILE" as const;
export const APP_DELETE_USER_PROFILE = "APP_DELETE_USER_PROFILE" as const;
export const APP_UPDATE_ORGANIZATION = "APP_UPDATE_ORGANIZATION" as const;
export const APP_DELETE_ORGANIZATION = "APP_DELETE_ORGANIZATION" as const;
export const APP_UPDATE_ORGANIZATION_MEMBER = "APP_UPDATE_ORGANIZATION_MEMBER" as const;
export const APP_UPDATE_USER_GUIDE_MODAL = "APP_UPDATE_USER_GUIDE_MODAL" as const;

// Driver Report
export const DRIVER_REPORT_UPDATE_SEARCH_CONDITIONS = "DRIVER_REPORT_UPDATE_SEARCH_CONDITIONS" as const;
export const DRIVER_REPORT_UPDATE_SEARCH_QUERY_STRING = "DRIVER_REPORT_UPDATE_SEARCH_QUERY_STRING" as const;

// Organization Member
export const ORGANIZATION_MEMBER_UPDATE_SEARCH_CONDITIONS = "ORGANIZATION_MEMBER_UPDATE_SEARCH_CONDITIONS" as const;
export const ORGANIZATION_MEMBER_UPDATE_SEARCH_QUERY_STRING = "ORGANIZATION_MEMBER_UPDATE_SEARCH_QUERY_STRING" as const;

// Maintenance Type
export const MAINTENANCE_TYPE_UPDATE_SEARCH_CONDITIONS = "MAINTENANCE_TYPE_UPDATE_SEARCH_CONDITIONS" as const;
export const MAINTENANCE_TYPE_UPDATE_SEARCH_QUERY_STRING = "MAINTENANCE_TYPE_UPDATE_SEARCH_QUERY_STRING" as const;

// Merchandise Type
export const MERCHANDISE_TYPE_UPDATE_SEARCH_CONDITIONS = "MERCHANDISE_TYPE_UPDATE_SEARCH_CONDITIONS" as const;
export const MERCHANDISE_TYPE_UPDATE_SEARCH_QUERY_STRING = "MERCHANDISE_TYPE_UPDATE_SEARCH_QUERY_STRING" as const;

// Unit Of Measure
export const UNIT_OF_MEASURE_UPDATE_SEARCH_CONDITIONS = "UNIT_OF_MEASURE_UPDATE_SEARCH_CONDITIONS" as const;
export const UNIT_OF_MEASURE_UPDATE_SEARCH_QUERY_STRING = "UNIT_OF_MEASURE_UPDATE_SEARCH_QUERY_STRING" as const;

// Maintenance
export const MAINTENANCE_UPDATE_SEARCH_CONDITIONS = "MAINTENANCE_UPDATE_SEARCH_CONDITIONS" as const;
export const MAINTENANCE_UPDATE_SEARCH_QUERY_STRING = "MAINTENANCE_UPDATE_SEARCH_QUERY_STRING" as const;

// Advance
export const ADVANCE_UPDATE_SEARCH_CONDITIONS = "ADVANCE_UPDATE_SEARCH_CONDITIONS" as const;
export const ADVANCE_UPDATE_SEARCH_QUERY_STRING = "ADVANCE_UPDATE_SEARCH_QUERY_STRING" as const;

// Trailer Type
export const TRAILER_TYPE_UPDATE_SEARCH_CONDITIONS = "TRAILER_TYPE_UPDATE_SEARCH_CONDITIONS" as const;
export const TRAILER_TYPE_UPDATE_SEARCH_QUERY_STRING = "TRAILER_TYPE_UPDATE_SEARCH_QUERY_STRING" as const;

// Vehicle Type
export const VEHICLE_TYPE_UPDATE_SEARCH_CONDITIONS = "VEHICLE_TYPE_UPDATE_SEARCH_CONDITIONS" as const;
export const VEHICLE_TYPE_UPDATE_SEARCH_QUERY_STRING = "VEHICLE_TYPE_UPDATE_SEARCH_QUERY_STRING" as const;

// Customer
export const CUSTOMER_UPDATE_SEARCH_CONDITIONS = "CUSTOMER_UPDATE_SEARCH_CONDITIONS" as const;
export const CUSTOMER_UPDATE_SEARCH_QUERY_STRING = "CUSTOMER_UPDATE_SEARCH_QUERY_STRING" as const;
export const CUSTOMER_UPDATE_CUSTOMER_ID = "CUSTOMER_UPDATE_CUSTOMER_ID" as const;

// Custom Fields
export const CUSTOM_FIELD_UPDATE_SEARCH_CONDITIONS = "CUSTOM_FIELD_UPDATE_SEARCH_CONDITIONS" as const;
export const CUSTOM_FIELD_UPDATE_SEARCH_QUERY_STRING = "CUSTOM_FIELD_UPDATE_SEARCH_QUERY_STRING" as const;

// Driver License Type
export const DRIVER_LICENSE_TYPE_UPDATE_SEARCH_CONDITIONS = "DRIVER_LICENSE_TYPE_UPDATE_SEARCH_CONDITIONS" as const;
export const DRIVER_LICENSE_TYPE_UPDATE_SEARCH_QUERY_STRING = "DRIVER_LICENSE_TYPE_UPDATE_SEARCH_QUERY_STRING" as const;

// Trailer
export const TRAILER_UPDATE_SEARCH_CONDITIONS = "TRAILER_UPDATE_SEARCH_CONDITIONS" as const;
export const TRAILER_UPDATE_SEARCH_QUERY_STRING = "TRAILER_UPDATE_SEARCH_QUERY_STRING" as const;

// Vehicle
export const VEHICLE_UPDATE_SEARCH_CONDITIONS = "VEHICLE_UPDATE_SEARCH_CONDITIONS" as const;
export const VEHICLE_UPDATE_SEARCH_QUERY_STRING = "VEHICLE_UPDATE_SEARCH_QUERY_STRING" as const;

// Driver License Type
export const SUBCONTRACTOR_UPDATE_SEARCH_CONDITIONS = "SUBCONTRACTOR_UPDATE_SEARCH_CONDITIONS" as const;
export const SUBCONTRACTOR_UPDATE_SEARCH_QUERY_STRING = "SUBCONTRACTOR_UPDATE_SEARCH_QUERY_STRING" as const;

// Driver
export const DRIVER_UPDATE_SEARCH_CONDITIONS = "DRIVER_UPDATE_SEARCH_CONDITIONS" as const;
export const DRIVER_UPDATE_SEARCH_QUERY_STRING = "DRIVER_UPDATE_SEARCH_QUERY_STRING" as const;

// Route
export const ROUTE_UPDATE_SEARCH_CONDITIONS = "ROUTE_UPDATE_SEARCH_CONDITIONS" as const;
export const ROUTE_RESET_SEARCH_CONDITIONS = "ROUTE_RESET_SEARCH_CONDITIONS" as const;
export const ROUTE_UPDATE_SEARCH_QUERY_STRING = "ROUTE_UPDATE_SEARCH_QUERY_STRING" as const;

// Order
export const ORDER_UPDATE_SEARCH_CONDITIONS = "ORDER_UPDATE_SEARCH_CONDITIONS" as const;
export const ORDER_UPDATE_SEARCH_QUERY_STRING = "ORDER_UPDATE_SEARCH_QUERY_STRING" as const;
export const ORDER_UPDATE_ORDER_DETAIL = "ORDER_UPDATE_ORDER_DETAIL" as const;
export const ORDER_CLEAR_ORDER_DETAIL = "ORDER_CLEAR_ORDER_DETAIL" as const;
export const ORDER_UPDATE_NEW_ORDER_DATE = "ORDER_UPDATE_NEW_ORDER_DATE" as const;
export const ORDER_UPDATE_AVAILABLE_VEHICLES_SEARCH_CONDITIONS =
  "ORDER_UPDATE_AVAILABLE_VEHICLES_SEARCH_CONDITIONS" as const;

// Driver salary
export const DRIVER_SALARY_UPDATE_SEARCH_CONDITIONS = "DRIVER_SALARY_UPDATE_SEARCH_CONDITIONS" as const;
export const DRIVER_SALARY_UPDATE_SEARCH_QUERY_STRING = "DRIVER_SALARY_UPDATE_SEARCH_QUERY_STRING" as const;

// Notification
export const NOTIFICATION_UPDATE_HAVE_NEW_NOTIFICATION = "NOTIFICATION_UPDATE_HAVE_NEW_NOTIFICATION" as const;

// Gas Station
export const GAS_STATION_UPDATE_SEARCH_CONDITIONS = "GAS_STATION_UPDATE_SEARCH_CONDITIONS" as const;
export const GAS_STATION_UPDATE_SEARCH_QUERY_STRING = "GAS_STATION_UPDATE_SEARCH_QUERY_STRING" as const;

// Driver Report
export const DRIVER_EXPENSE_UPDATE_SEARCH_CONDITIONS = "DRIVER_EXPENSE_UPDATE_SEARCH_CONDITIONS" as const;
export const DRIVER_EXPENSE_UPDATE_SEARCH_QUERY_STRING = "DRIVER_EXPENSE_UPDATE_SEARCH_QUERY_STRING" as const;

// Fuel log
export const FUEL_LOG_UPDATE_SEARCH_CONDITIONS = "FUEL_LOG_UPDATE_SEARCH_CONDITIONS" as const;
export const FUEL_LOG_UPDATE_SEARCH_QUERY_STRING = "FUEL_LOG_UPDATE_SEARCH_QUERY_STRING" as const;

// Order Monitoring
export const ORDER_MONITORING_UPDATE_SEARCH_CONDITIONS = "ORDER_MONITORING_UPDATE_SEARCH_CONDITIONS" as const;
export const ORDER_MONITORING_UPDATE_SEARCH_QUERY_STRING = "ORDER_MONITORING_UPDATE_SEARCH_QUERY_STRING" as const;

// Vehicle group
export const VEHICLE_GROUP_UPDATE_SEARCH_CONDITIONS = "VEHICLE_GROUP_UPDATE_SEARCH_CONDITIONS" as const;
export const VEHICLE_GROUP_UPDATE_SEARCH_QUERY_STRING = "VEHICLE_GROUP_UPDATE_SEARCH_QUERY_STRING" as const;

// Customer group
export const CUSTOMER_GROUP_UPDATE_SEARCH_CONDITIONS = "CUSTOMER_GROUP_UPDATE_SEARCH_CONDITIONS" as const;
export const CUSTOMER_GROUP_UPDATE_SEARCH_QUERY_STRING = "CUSTOMER_GROUP_UPDATE_SEARCH_QUERY_STRING" as const;
export const CUSTOMER_GROUP_UPDATE_AVAILABLE_CUSTOMER_SEARCH_CONDITIONS =
  "CUSTOMER_GROUP_UPDATE_AVAILABLE_CUSTOMER_SEARCH_CONDITIONS" as const;

// Customer Report
export const CUSTOMER_REPORT_UPDATE_SEARCH_CONDITIONS = "CUSTOMER_REPORT_UPDATE_SEARCH_CONDITIONS" as const;
export const CUSTOMER_REPORT_UPDATE_SEARCH_QUERY_STRING = "CUSTOMER_REPORT_UPDATE_SEARCH_QUERY_STRING" as const;

// Monitoring Vehicles
export const MONITORING_VEHICLES_UPDATE_SEARCH_CONDITIONS = "MONITORING_VEHICLES_UPDATE_SEARCH_CONDITIONS" as const;
export const MONITORING_VEHICLES_UPDATE_SEARCH_QUERY_STRING = "MONITORING_VEHICLES_UPDATE_SEARCH_QUERY_STRING" as const;

// Subcontractor cost
export const SUBCONTRACTOR_COST_UPDATE_SEARCH_CONDITIONS = "SUBCONTRACTOR_COST_UPDATE_SEARCH_CONDITIONS" as const;
export const SUBCONTRACTOR_COST_UPDATE_SEARCH_QUERY_STRING = "SUBCONTRACTOR_COST_UPDATE_SEARCH_QUERY_STRING" as const;
